=== bakkdoor/v-unit/data/customers.dtd
<!ELEMENT customers (customer*)>
<!ELEMENT customer EMPTY>

<!ATTLIST customers minID NMTOKEN #REQUIRED>
<!ATTLIST customer 	cID NMTOKEN #REQUIRED
					firtName CDATA #REQUIRED
					lastName CDATA #REQUIRED
					birthDate NMTOKEN #REQUIRED
					street CDATA #REQUIRED						
					houseNr NMTOKEN #REQUIRED
					zipCode NMTOKEN #REQUIRED
					city CDATA #REQUIRED
					identificationNr NMTOKEN #REQUIRED
					title (Herr|Frau) #REQUIRED>

=== bakkdoor/v-unit/data/customers.xml
<?xml version="1.0" standalone="yes"?><!DOCTYPE customers PUBLIC 'customerList' 'customers.dtd'>
<customers minID='40'><customer title='Herr' birthDate='1:1:1920' lastName='aus Tirol' street='AAAAAAH' firstName='Anton' city='BBBBBBBBBBB' identificationNr='' zipCode='432234' houseNr='213' cID='34'></customer><customer title='Herr' birthDate='1:1:1900' lastName='oauihgrbsydfvb' street='oijklmoipj' firstName='woueghfwnkbv' city='iaeurghjkvylnsrgejhdbk' identificationNr='oa89weu4t0ujinergkd' zipCode='3458' houseNr='765' cID='35'></customer><customer title='Herr' birthDate='3:2:1987' lastName='Bertels' street='Woerthstr.' firstName='Christopher' city='Osnabrueck' identificationNr='123456789ABCDEFG' zipCode='49082' houseNr='7' cID='1'></customer><customer title='Herr' birthDate='1:1:1970' lastName='Mustermann' street='Wasserweg' firstName='Max' city='Musterhausen' identificationNr='ABCDEFG123456789' zipCode='12345' houseNr='1' cID='2'></customer><customer title='Herr' birthDate='1:1:1900' lastName='oauihgrbsydfvb' street='a' firstName='woueghfwnkbv' city='tr' identificationNr='oa89weu4t0ujinergkd' zipCode='3458' houseNr='765' cID='38'></customer><customer title='Herr' birthDate='1:1:1900' lastName='oauihgrbsydfvb' street='1are' firstName='woueghfwnkbv' city='1a' identificationNr='oa89weu4t0ujinergkd' zipCode='3458' houseNr='765' cID='39'></customer><customer title='Herr' birthDate='1:1:1900' lastName='oauihgrbsydfvb' street='oijklmoipj' firstName='woueghfwnkbv' city='iaeurghjkvylnsrgejhdbk' identificationNr='oa89weu4t0ujinergkd' zipCode='3458' houseNr='765' cID='36'></customer><customer title='Herr' birthDate='1:1:1900' lastName='oauihgrbsydfvb' street='dfr' firstName='woueghfwnkbv' city='iaeurghjkvylnsrgejhdbk' identificationNr='oa89weu4t0ujinergkd' zipCode='3458' houseNr='765' cID='37'></customer></customers>
