=== bakkdoor/v-unit/data/videos.dtd
<!ELEMENT videos (video*)>
<!ELEMENT video (videoUnit*)>
<!ELEMENT videoUnit EMPTY>

<!ATTLIST videos 	minID NMTOKEN #REQUIRED>
<!ATTLIST video 	vID NMTOKEN #REQUIRED
					title CDATA #REQUIRED
					releaseYear NMTOKEN #REQUIRED
					priceCategoryID NMTOKEN #REQUIRED
					ratedAge NMTOKEN #REQUIRED>
<!ATTLIST videoUnit	uID NMTOKEN #REQUIRED
					videoID NMTOKEN #REQUIRED>

=== bakkdoor/v-unit/data/videos.xml
<?xml version="1.0" standalone="yes"?><!DOCTYPE videos PUBLIC 'videoList' 'videos.dtd'>
<videos minID='46' minVideoUnitID='184'><video vID='1' priceCategoryID='13' title='Die Verurteilten' ratedAge='12' releaseYear='1995'><videoUnit videoID='1' uID='1'></videoUnit><videoUnit videoID='1' uID='2'></videoUnit><videoUnit videoID='1' uID='3'></videoUnit></video><video vID='2' priceCategoryID='13' title='Der Pate' ratedAge='16' releaseYear='1972'><videoUnit videoID='2' uID='4'></videoUnit><videoUnit videoID='2' uID='5'></videoUnit><videoUnit videoID='2' uID='6'></videoUnit><videoUnit videoID='2' uID='7'></videoUnit></video><video vID='3' priceCategoryID='2' title='The Dark Knight' ratedAge='16' releaseYear='2008'><videoUnit videoID='3' uID='8'></videoUnit><videoUnit videoID='3' uID='9'></videoUnit><videoUnit videoID='3' uID='10'></videoUnit><videoUnit videoID='3' uID='11'></videoUnit><videoUnit videoID='3' uID='12'></videoUnit><videoUnit videoID='3' uID='13'></videoUnit><videoUnit videoID='3' uID='14'></videoUnit><videoUnit videoID='3' uID='15'></videoUnit><videoUnit videoID='3' uID='17'></videoUnit><videoUnit videoID='3' uID='16'></videoUnit></video><video vID='5' priceCategoryID='13' title='Zwei glorreiche Halunken' ratedAge='16' releaseYear='1966'><videoUnit videoID='5' uID='23'></videoUnit><videoUnit videoID='5' uID='22'></videoUnit><videoUnit videoID='5' uID='24'></videoUnit></video><video vID='6' priceCategoryID='13' title='Pulp Fiction' ratedAge='16' releaseYear='1994'><videoUnit videoID='6' uID='25'></videoUnit><videoUnit videoID='6' uID='27'></videoUnit><videoUnit videoID='6' uID='26'></videoUnit><videoUnit videoID='6' uID='28'></videoUnit></video><video vID='7' priceCategoryID='13' title='Schindlers Liste' ratedAge='12' releaseYear='1993'><videoUnit videoID='7' uID='29'></videoUnit><videoUnit videoID='7' uID='31'></videoUnit><videoUnit videoID='7' uID='30'></videoUnit><videoUnit videoID='7' uID='32'></videoUnit></video><video vID='10' priceCategoryID='1' title='Casablanca' ratedAge='6' releaseYear='1942'><videoUnit videoID='10' uID='39'></videoUnit><videoUnit videoID='10' uID='40'></videoUnit></video><video vID='11' priceCategoryID='13' title='Star Wars - Krieg der Sterne' ratedAge='12' releaseYear='1977'><videoUnit videoID='11' uID='42'></videoUnit><videoUnit videoID='11' uID='43'></videoUnit><videoUnit videoID='11' uID='41'></videoUnit><videoUnit videoID='11' uID='44'></videoUnit></video><video vID='14' priceCategoryID='13' title='Star Wars - Das Imperium schlägt zurueck' ratedAge='12' releaseYear='1980'><videoUnit videoID='14' uID='55'></videoUnit><videoUnit videoID='14' uID='56'></videoUnit><videoUnit videoID='14' uID='57'></videoUnit><videoUnit videoID='14' uID='58'></videoUnit></video><video vID='15' priceCategoryID='13' title='Star Wars - Die Rueckkehr der Jedi-Ritter' ratedAge='12' releaseYear='1983'><videoUnit videoID='15' uID='59'></videoUnit><videoUnit videoID='15' uID='60'></videoUnit><videoUnit videoID='15' uID='61'></videoUnit><videoUnit videoID='15' uID='62'></videoUnit><videoUnit videoID='15' uID='63'></videoUnit></video><video vID='17' priceCategoryID='2' title='Der Herr der Ringe - Die Gefährten' ratedAge='12' releaseYear='2001'><videoUnit videoID='17' uID='65'></videoUnit><videoUnit videoID='17' uID='66'></videoUnit><videoUnit videoID='17' uID='67'></videoUnit><videoUnit videoID='17' uID='68'></videoUnit></video><video vID='19' priceCategoryID='2' title='Der Herr der Ringe - Die Rückkehr des Königs' ratedAge='12' releaseYear='2003'><videoUnit videoID='19' uID='75'></videoUnit><videoUnit videoID='19' uID='76'></videoUnit><videoUnit videoID='19' uID='77'></videoUnit><videoUnit videoID='19' uID='78'></videoUnit><videoUnit videoID='19' uID='79'></videoUnit><videoUnit videoID='19' uID='80'></videoUnit><videoUnit videoID='19' uID='81'></videoUnit><videoUnit videoID='19' uID='82'></videoUnit></video><video vID='18' priceCategoryID='2' title='Der Herr der Ringe - Die Zwei Türme' ratedAge='12' releaseYear='2002'><videoUnit videoID='18' uID='69'></videoUnit><videoUnit videoID='18' uID='70'></videoUnit><videoUnit videoID='18' uID='71'></videoUnit><videoUnit videoID='18' uID='72'></videoUnit><videoUnit videoID='18' uID='73'></videoUnit><videoUnit videoID='18' uID='74'></videoUnit></video><video vID='21' priceCategoryID='13' title='Indiana Jones - Jäger des verlorenen Schatzes' ratedAge='16' releaseYear='1981'><videoUnit videoID='21' uID='86'></videoUnit><videoUnit videoID='21' uID='87'></videoUnit><videoUnit videoID='21' uID='88'></videoUnit></video><video vID='20' priceCategoryID='13' title='GoodFellas - Drei Jahrzehnte in der Mafia' ratedAge='16' releaseYear='1990'><videoUnit videoID='20' uID='83'></videoUnit><videoUnit videoID='20' uID='84'></videoUnit><videoUnit videoID='20' uID='85'></videoUnit></video><video vID='23' priceCategoryID='13' title='Indiana Jones und der letzte Kreuzzug' ratedAge='12' releaseYear='1989'><videoUnit videoID='23' uID='93'></videoUnit><videoUnit videoID='23' uID='94'></videoUnit><videoUnit videoID='23' uID='95'></videoUnit><videoUnit videoID='23' uID='96'></videoUnit></video><video vID='22' priceCategoryID='13' title='Indiana Jones und der Tempel des Todes' ratedAge='16' releaseYear='1984'><videoUnit videoID='22' uID='89'></videoUnit><videoUnit videoID='22' uID='90'></videoUnit><videoUnit videoID='22' uID='91'></videoUnit><videoUnit videoID='22' uID='92'></videoUnit></video><video vID='25' priceCategoryID='13' title='Fight Club' ratedAge='18' releaseYear='1999'><videoUnit videoID='25' uID='107'></videoUnit><videoUnit videoID='25' uID='108'></videoUnit><videoUnit videoID='25' uID='109'></videoUnit></video><video vID='24' priceCategoryID='2' title='Indiana Jones und das Königreich des Kristallschädels' ratedAge='12' releaseYear='2008'><videoUnit videoID='24' uID='97'></videoUnit><videoUnit videoID='24' uID='98'></videoUnit><videoUnit videoID='24' uID='99'></videoUnit><videoUnit videoID='24' uID='100'></videoUnit><videoUnit videoID='24' uID='101'></videoUnit><videoUnit videoID='24' uID='102'></videoUnit><videoUnit videoID='24' uID='103'></videoUnit><videoUnit videoID='24' uID='104'></videoUnit><videoUnit videoID='24' uID='105'></videoUnit><videoUnit videoID='24' uID='106'></videoUnit></video><video vID='27' priceCategoryID='1' title='Citizen Kane' ratedAge='16' releaseYear='1941'><videoUnit videoID='27' uID='113'></videoUnit><videoUnit videoID='27' uID='114'></videoUnit></video><video vID='26' priceCategoryID='13' title='Das Schweigen der Lämmer' ratedAge='16' releaseYear='1991'><videoUnit videoID='26' uID='110'></videoUnit><videoUnit videoID='26' uID='111'></videoUnit><videoUnit videoID='26' uID='112'></videoUnit></video><video vID='29' priceCategoryID='2' title='Das Leben der Anderen' ratedAge='12' releaseYear='2006'><videoUnit videoID='29' uID='119'></videoUnit><videoUnit videoID='29' uID='120'></videoUnit><videoUnit videoID='29' uID='121'></videoUnit><videoUnit videoID='29' uID='122'></videoUnit><videoUnit videoID='29' uID='123'></videoUnit></video><video vID='28' priceCategoryID='13' title='Forrest Gump' ratedAge='12' releaseYear='1994'><videoUnit videoID='28' uID='115'></videoUnit><videoUnit videoID='28' uID='116'></videoUnit><videoUnit videoID='28' uID='117'></videoUnit><videoUnit videoID='28' uID='118'></videoUnit></video><video vID='31' priceCategoryID='13' title='Donnie Darko' ratedAge='16' releaseYear='2001'><videoUnit videoID='31' uID='129'></videoUnit><videoUnit videoID='31' uID='130'></videoUnit><videoUnit videoID='31' uID='131'></videoUnit><videoUnit videoID='31' uID='132'></videoUnit></video><video vID='30' priceCategoryID='2' title='Prestige - Die Meister der Magie' ratedAge='12' releaseYear='2006'><videoUnit videoID='30' uID='124'></videoUnit><videoUnit videoID='30' uID='125'></videoUnit><videoUnit videoID='30' uID='126'></videoUnit><videoUnit videoID='30' uID='127'></videoUnit><videoUnit videoID='30' uID='128'></videoUnit></video><video vID='34' priceCategoryID='13' title='Madagascar' ratedAge='0' releaseYear='2005'><videoUnit videoID='34' uID='147'></videoUnit><videoUnit videoID='34' uID='148'></videoUnit><videoUnit videoID='34' uID='149'></videoUnit><videoUnit videoID='34' uID='150'></videoUnit><videoUnit videoID='34' uID='151'></videoUnit><videoUnit videoID='34' uID='152'></videoUnit></video><video vID='35' priceCategoryID='13' title='Findet Nemo' ratedAge='6' releaseYear='2003'><videoUnit videoID='35' uID='153'></videoUnit><videoUnit videoID='35' uID='154'></videoUnit><videoUnit videoID='35' uID='155'></videoUnit><videoUnit videoID='35' uID='156'></videoUnit><videoUnit videoID='35' uID='157'></videoUnit></video><video vID='32' priceCategoryID='2' title='Gladiator' ratedAge='16' releaseYear='2000'><videoUnit videoID='32' uID='133'></videoUnit><videoUnit videoID='32' uID='134'></videoUnit><videoUnit videoID='32' uID='135'></videoUnit><videoUnit videoID='32' uID='136'></videoUnit></video><video vID='33' priceCategoryID='2' title='Ratatouille' ratedAge='0' releaseYear='2007'><videoUnit videoID='33' uID='137'></videoUnit><videoUnit videoID='33' uID='138'></videoUnit><videoUnit videoID='33' uID='139'></videoUnit><videoUnit videoID='33' uID='140'></videoUnit><videoUnit videoID='33' uID='141'></videoUnit><videoUnit videoID='33' uID='142'></videoUnit><videoUnit videoID='33' uID='143'></videoUnit><videoUnit videoID='33' uID='144'></videoUnit><videoUnit videoID='33' uID='145'></videoUnit><videoUnit videoID='33' uID='146'></videoUnit></video><video vID='38' priceCategoryID='1' title='Der König der Löwen' ratedAge='0' releaseYear='1994'><videoUnit videoID='38' uID='164'></videoUnit><videoUnit videoID='38' uID='165'></videoUnit><videoUnit videoID='38' uID='166'></videoUnit></video><video vID='39' priceCategoryID='2' title='Little Miss Sunshine' ratedAge='6' releaseYear='2006'><videoUnit videoID='39' uID='167'></videoUnit><videoUnit videoID='39' uID='168'></videoUnit><videoUnit videoID='39' uID='169'></videoUnit><videoUnit videoID='39' uID='170'></videoUnit></vid
